### ISSUE TITLE
BUG: error parsing dnsdumpster

### ISSUE THREAD

**Issue by royharoush** [aboul3la/Sublist3r#11]
hi,

the error is 
```

[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
Process DNSdumpster-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 549, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 604, in enumerate
    self.extract_domains(post_resp)
  File "sublist3r.py", line 611, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
IndexError: list index out of range
```
thanks,

roy

**Comment by aboul3la** [comment]
Hi  @royharoush,

Does the error appears every time you run it or it appeared only once ?

**Comment by royharoush** [comment]
it seems to appear every time i run it.
i ran this tool on 30~ domains,and the error appeared in each one of the
outputs.
i can test again today.

**Comment by aboul3la** [comment]
Can you please try it again today and let me know if you still see this error ? as from my own tests i don't see the error appears.

**Comment by mtrovo** [comment]
Just cloned the repo and I'm getting  the same error. 

Sending below the stacktrace:

```
Process DNSdumpster-7:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 549, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 604, in enumerate
    self.extract_domains(post_resp)
  File "sublist3r.py", line 611, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
IndexError: list index out of range
```

**Comment by royharoush** [comment]
for some reason it doesnt happen anymore, and im not sure how i fixed it :|
i think it was one of the prerequisites which was missing.

**Comment by aboul3la** [comment]
Thanks @royharoush for the heads up. Sometimes error like this occurred when there is a problem with the DNSdumpster service itself or with your Internet connection.  

@mtrovo can you please tell me if you still also see that error ?

**Comment by pr0letariat** [comment]
I just cloned the repo again but unfortunately this issue still exists.

```
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/path/Sublist3r/sublist3r.py", line 565, in run
    domain_list = self.enumerate()
  File "/path/Sublist3r/sublist3r.py", line 625, in enumerate
    token = self.get_csrftoken(resp)
  File "/path/Sublist3r/sublist3r.py", line 620, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer


```
